/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package neuron;

import java.lang.management.BufferPoolMXBean;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author abner
 */
public class Parametros extends javax.swing.JFrame {

    /**
     * Creates new form Parametros
     */
    public Parametros() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    double forma, apariencia, consistencia, peso, color, rango_peso;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_formaCircular = new javax.swing.JButton();
        btn_formaCorazon = new javax.swing.JButton();
        btn_consistenciaBlanda = new javax.swing.JButton();
        btn_consistenciaDura = new javax.swing.JButton();
        btn_aparienciaAspera = new javax.swing.JButton();
        btn_aparienciaLisa = new javax.swing.JButton();
        btn_colorRojo = new javax.swing.JButton();
        btn_colorNaranja = new javax.swing.JButton();
        btn_colorAmarillo = new javax.swing.JButton();
        btn_colorVerde = new javax.swing.JButton();
        text_peso = new javax.swing.JTextField();
        btn_volver = new javax.swing.JButton();
        btn_calcular = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_formaCircular.setText("Circular");
        btn_formaCircular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formaCircularActionPerformed(evt);
            }
        });
        jPanel1.add(btn_formaCircular, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        btn_formaCorazon.setText("Corazón");
        btn_formaCorazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formaCorazonActionPerformed(evt);
            }
        });
        jPanel1.add(btn_formaCorazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        btn_consistenciaBlanda.setText("Blanda");
        btn_consistenciaBlanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consistenciaBlandaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_consistenciaBlanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        btn_consistenciaDura.setText("Dura");
        btn_consistenciaDura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consistenciaDuraActionPerformed(evt);
            }
        });
        jPanel1.add(btn_consistenciaDura, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        btn_aparienciaAspera.setText("Aspera");
        btn_aparienciaAspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aparienciaAsperaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_aparienciaAspera, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        btn_aparienciaLisa.setText("Lisa");
        btn_aparienciaLisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aparienciaLisaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_aparienciaLisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 70, -1));

        btn_colorRojo.setForeground(new java.awt.Color(255, 0, 0));
        btn_colorRojo.setText("Rojo");
        btn_colorRojo.setActionCommand("Rojo");
        btn_colorRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colorRojoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_colorRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 80, -1));

        btn_colorNaranja.setForeground(new java.awt.Color(255, 102, 51));
        btn_colorNaranja.setText("Naranja");
        btn_colorNaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colorNaranjaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_colorNaranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        btn_colorAmarillo.setText("Amarillo");
        btn_colorAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colorAmarilloActionPerformed(evt);
            }
        });
        jPanel1.add(btn_colorAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        btn_colorVerde.setForeground(new java.awt.Color(0, 102, 51));
        btn_colorVerde.setText("Verde");
        btn_colorVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colorVerdeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_colorVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 80, -1));

        text_peso.setToolTipText("");
        text_peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_pesoActionPerformed(evt);
            }
        });
        jPanel1.add(text_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 292, 150, 50));

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        btn_calcular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });
        jPanel1.add(btn_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Describe la fruta.jpg"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        String formas=null;
        if (forma ==1) {
            formas="Circular";
        }else{
            formas="Corazón";
        }
        
        String consistencias=null;
        if (consistencia == 1) {
            consistencias="Blanda";
        }else{
            consistencias="Dura";
        }
        
        String apariencias=null;
        if (apariencia == 1) {
            apariencias="Aspera";
        }else{
            apariencias="Lisa";
        }
        
        String colores = null;
        if (color == -1) {
            colores="Rojo";
        }
        if (color == 1) {
            colores="Naranja";
        }
        if (color == .25) {
            colores="Amarillo";
        }
        if (color == -.25){
            colores="Verde";       
        }
        
        String pesogramos;
        pesogramos = text_peso.getText();
        JOptionPane.showConfirmDialog(null, "La descripción de su fruta fué:\nForma: "+formas+"\nConsistencia: "+consistencias+"\nApariencia: "+apariencias+"\nPeso: "+pesogramos+"gr\nColor: "+colores);
        
        double x1 = forma;
        double x2 = consistencia;
        double x3 = apariencia;
        double x4 = rango_peso;
        double x5 = color;
        
        //Creamos el objeto neurona de la clase Perceptron
        Perceptron neurona = new Perceptron();
        
        //Usamos el metodo "procesos" de la clase Perceptron para calcular el resultado
        if (neurona.proceso(x1, x2, x3, x4, x5, 10)==1) {
            JOptionPane.showConfirmDialog(null, "Tu fruta es una:\nNARANJA");
        }else{
            JOptionPane.showConfirmDialog(null, "Tu fruta es una:\nMANZANA");
        }
        
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        Index regresar = new Index();
        regresar.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_formaCircularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formaCircularActionPerformed
        forma = 1;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_formaCircularActionPerformed

    private void btn_formaCorazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formaCorazonActionPerformed
        forma = 0;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_formaCorazonActionPerformed

    private void btn_consistenciaBlandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consistenciaBlandaActionPerformed
        consistencia = 1;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consistenciaBlandaActionPerformed

    private void btn_consistenciaDuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consistenciaDuraActionPerformed
        consistencia = -1;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consistenciaDuraActionPerformed

    private void btn_aparienciaAsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aparienciaAsperaActionPerformed
        apariencia = 1;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aparienciaAsperaActionPerformed

    private void btn_aparienciaLisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aparienciaLisaActionPerformed
        apariencia = -1;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aparienciaLisaActionPerformed

    private void text_pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_pesoActionPerformed
        String pesogramos;
        pesogramos = text_peso.getText();
        peso=Double.parseDouble(pesogramos);
        
        if (peso > 100 && peso <= 130) {
            rango_peso = 1;
        }else if (peso > 130 && peso <= 160){
            rango_peso = .5;
        }else if (peso > 160 && peso <= 185) {
            rango_peso = -.5;
        }else if (peso > 185 && peso <= 210) {
            rango_peso = 1;
        }else{
            JOptionPane.showMessageDialog(null, "El peso de la fruta no se encuentra en el rango");
        }
        System.out.println("peso "+peso);
        /*
        if (peso < 100 || peso > 220) {
            JOptionPane.showMessageDialog(null, "El peso de la fruta no se encuentra en el rango");
        }*/
        // TODO add your handling code here:
    }//GEN-LAST:event_text_pesoActionPerformed

    private void btn_colorRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_colorRojoActionPerformed
        color = -1;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_colorRojoActionPerformed

    private void btn_colorNaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_colorNaranjaActionPerformed
        color = 1;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_colorNaranjaActionPerformed

    private void btn_colorAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_colorAmarilloActionPerformed
        color = .25;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_colorAmarilloActionPerformed

    private void btn_colorVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_colorVerdeActionPerformed
        color = -.25;
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_colorVerdeActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parametros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_aparienciaAspera;
    private javax.swing.JButton btn_aparienciaLisa;
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_colorAmarillo;
    private javax.swing.JButton btn_colorNaranja;
    private javax.swing.JButton btn_colorRojo;
    private javax.swing.JButton btn_colorVerde;
    private javax.swing.JButton btn_consistenciaBlanda;
    private javax.swing.JButton btn_consistenciaDura;
    private javax.swing.JButton btn_formaCircular;
    private javax.swing.JButton btn_formaCorazon;
    private javax.swing.JButton btn_volver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField text_peso;
    // End of variables declaration//GEN-END:variables
}
